# Generated by Django 3.1.3 on 2020-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('password2', models.CharField(max_length=300)),
            ],
        ),
    ]
