# Generated by Django 3.1.3 on 2020-12-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='bname',
            field=models.CharField(max_length=200, unique='True'),
        ),
    ]
